"""
Background tasks for calculator app using Django-Q.

These tasks run asynchronously to avoid blocking user requests.
"""

from django.core.mail import send_mail
from django.conf import settings
from .models import Scenario
from .phase_calculator import calculate_accumulation_phase


def send_scenario_email(scenario_id, user_email):
    """
    Background task to send scenario report via email.

    Args:
        scenario_id: ID of the scenario to email
        user_email: Email address to send to
    """
    try:
        scenario = Scenario.objects.get(pk=scenario_id)
    except Scenario.DoesNotExist:
        return f"Error: Scenario {scenario_id} not found (may have been deleted)"

    try:
        # Calculate results
        results = calculate_accumulation_phase(scenario.data)

        # Format email body
        email_body = f"""
Retirement Scenario Report: {scenario.name}

=== Phase 1: Accumulation ===
Years to Retirement: {results.years_to_retirement}
Final Portfolio Value: ${results.future_value:,.2f}
Total Personal Contributions: ${results.total_personal_contributions:,.2f}
Total Employer Match: ${results.total_employer_contributions:,.2f}
Investment Gains: ${results.investment_gains:,.2f}

This report was generated by Retirement Planner.
        """

        # Send email
        send_mail(
            subject=f'Retirement Scenario: {scenario.name}',
            message=email_body,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user_email],
            fail_silently=False,
        )

        return f"Email sent successfully to {user_email}"

    except Exception as e:
        return f"Error sending email: {str(e)}"
